
development:
  adapter: postgresql
  encoding: unicode
  database: blog-master_development
  pool: 5
  username: nithin
  password: nithin
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  database: blog-master_test
  pool: 5
  username: nithin
  password: nithin
  timeout: 5000

